name: Aianyone
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28944524261169136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b0c'
    - '#75a0fe'
    - '#427dfd'
    - '#484848'
    - '#808080'
  brandStrength: 0.813829930499196
  lightness: 0.3897120850160718
  saturation: 0.685689021134749
  rhythmicContrast: 0.9934205082245171
purpose: []
